# Mock config_forex.py for sanity test
OPTIMIZER_OUTPUT = "optimizer_output_forex"
FOREX_PAIRS = {}
OPTUNA_N_TRIALS = 10
OPTUNA_TIMEOUT = 30
SYMBOL_MAP = {}
MT5_TERMINAL_PATH = None
DATA_DIR = "data"
OPTIMIZER_USE_SECTOR_MAP = False
OPTIMIZER_USE_DYNAMIC_SELECTED_ASSETS = False
OPTIMIZER_APPLY_MT5_MARKET_WATCH_FILTER = False
TIMEFRAME_M15 = 15
TIMEFRAME_M30 = 30
TIMEFRAME_M5 = 5
TIMEFRAME_H1 = 60
ML_MIN_RETURN = 0.0005
